### ISSUE TITLE
Proposal: detatch dockerfile-opam to its own repository in the ocurrent org

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/ocaml-dockerfile#38]
`dockerfile-opam` is a fast-changing library needed for `ocurrent/docker-base-images`.
Given that the rest of the library doesn't change much, and given that the libraries are already split, it seems relatively easy to give `dockerfile-opam` its own repository in the `ocurrent` org. This would avoid having to release three packages everytime something has to change (e.g. distributions breaking something, adding new distributions, …) and would make the management of it more centralized and easy to look for.

**Comment by avsm** [comment]
I'd prefer to keep these repositories integrated for the moment.   dockerfile-opam is useful outside of ocurrent as well.
